---
name: Quality gate
on:
    pull_request:
        branches:
            - master
jobs:
    quality-gate:
        name: Check code
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Install dependencies
              run: npm ci --fund=false --audit=false --legacy-peer-deps
            - name: Unit tests
              run: npm run test -- --watch=false
            - name: Code linter
              run: npm run lint
            - name: Check code formatting
              run: npm run format:check
