---
name: Vercel Production Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    TOLGEE_API_KEY: ${{ secrets.TOLGEE_API_KEY }}
    VITE_GTM_ID: ${{ secrets.VITE_GTM_ID }}
on:
    workflow_dispatch:
    push:
        branches:
            - master
jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            - name: Get translations from Tolgee
              run: npm ci --fund=false --audit=false --legacy-peer-deps && npm run translations:download:ci
            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel (Production)
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
